syms a0  a1 a2 a3 a4 a5 t T l_0w l_0a l_Tw l_Ta

s = a0 + a1 * t + a2 * t * t + a3 * t * t* t +a4 * t*t*t*t +a5 *t *t*t*t*t;


solve({subs(s, t, 0) == 0, ...
       subs(s, t, T) == 1, ...
       subs(jacobian(s, t), t, 0) == l_0w, ...
       subs(jacobian(s, t), t, T) == l_Tw, ...
       subs(jacobian(jacobian(s, t), t), t, 0) == l_0a, ...
       subs(jacobian(jacobian(s, t), t), t, T) == l_Ta}, ...
       [a0, a1, a2, a3, a4, a5])